# Generated by Django 4.2.16 on 2024-09-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "permissions": [
                    ("product_set_published_status", "Публиковать товар"),
                    ("product_change_description", "Изменять описание товара"),
                    ("product_change_category", "Изменять категорию товара"),
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="Доступно публике"),
        ),
    ]
